DIMS/routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SendMessageController;

/** this is a sample line */
use App\Http\Controllers\SampleController;

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AdminOfficersController;
use App\Http\Controllers\AdminMessageController;
use App\Http\Controllers\AdminEventsController;
use App\Http\Controllers\AdminMeetingsController;
use App\Http\Controllers\AdminAnnouncementsController;
use App\Http\Controllers\AdminSignoutController;
use App\Http\Controllers\AdminMessageSelectedController;
use App\Http\Controllers\AdminThemeController;
use App\Http\Controllers\AdminUploadFileController;

use App\Http\Controllers\OfficerDashboardController;
use App\Http\Controllers\OfficerOfficersController;
use App\Http\Controllers\OfficerMessageController;
use App\Http\Controllers\OfficerAccountController;
use App\Http\Controllers\OfficerSignoutController;
use App\Http\Controllers\OfficerThemeController;
use App\Http\Controllers\OfficerUploadProfileController;
use App\Http\Controllers\OfficerUploadFileController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::resource('/login', LoginController::class);
Route::resource('/register', RegisterController::class);

Route::resource('admin/dashboard', AdminDashboardController::class);
Route::resource('admin/officers', AdminOfficersController::class);
Route::resource('admin/messages', AdminMessageController::class);
Route::resource('admin/events', AdminEventsController::class);
Route::resource('admin/meetings', AdminMeetingsController::class);
Route::resource('admin/announcements', AdminAnnouncementsController::class);
Route::resource('admin/signout', AdminSignoutController::class);
Route::resource('admin/theme', AdminThemeController::class);
Route::resource('admin/open-message', AdminMessageController::class);
Route::resource('admin/message-selected', AdminMessageSelectedController::class);
Route::resource('admin/send-message', SendMessageController::class);
Route::resource('admin/upload-file', AdminUploadFileController::class);

Route::resource('officer/user-dashboard', OfficerDashboardController::class);
Route::resource('officer/user-officers', OfficerOfficersController::class);
Route::resource('officer/user-message', OfficerMessageController::class);
Route::resource('officer/user-account', OfficerAccountController::class);
Route::resource('officer/user-signout', OfficerSignoutController::class);
Route::resource('officer/send-message', SendMessageController::class);
Route::resource('officer/user-theme', OfficerThemeController::class);
Route::resource('officer/user-profile', OfficerUploadProfileController::class);
Route::resource('officer/upload-file', OfficerUploadFileController::class);

/** this is a sample line */
Route::resource('sample', SampleController::class);

Route::get('/game', function() {
    return view('game');
});

Route::get('/about', function () {
    return view('about');
});

DIMS/resources/views/admin/announcements.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/admin-css.php";?> 
        <?php if(session('admin-theme') == 'dark'){ include "addons/includes/admin-dark-css.php"; }?>   
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/admin-navbar.php";?>
        <?php include "addons/navigations/admin-sidebar.php";?>
        <div class="display-container">
                <div class="modal-header" style="border-left: solid white 1px">
                    <h6><span class='fa fa-bell'></span> Announcements</h6>
                    <div>
                        <button data-toggle="modal" data-target="#addAnnouncement" class="btn btn-sm"><span class="fa fa-plus"></span> Add Announcement</button>
                    </div>
                </div>
                <br>

                <div class="modal fade" aria-hidden="true" id="addAnnouncement">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <form action="{{ route('announcements.store' ) }}" method="POST">
                                @csrf
                                @method('POST')
                                <div class="modal-header">
                                    <h5><span class="fa fa-list"></span> Create New Announcement</h5>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label>Announcer</label>
                                        <input required type="text" class="form-control" name="announcer">
                                    </div>
                                    <div class="form-group">
                                        <label>Announcement</label>
                                        <textarea rows="10" required class="form-control" name="details"></textarea>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button data-dismiss="modal" class="btn btn-secondary btn-sm"><span class="fa fa-remove"></span> Cancel</button>
                                    <button type="submit" class="btn btn-success btn-sm"><span class="fa fa-save"></span> Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <table class="table-hover">
                    <tbody>
                        @foreach ($announcements as $announcement)
                        <tr style="display: flex; justify-content: space-between; border-bottom: solid 1px gray;">
                            <td class="ml-3" style="width: 850px;">
                                <h6><span class="fa fa-user"></span> {{ $announcement->announcer }} : {{ date('M d, Y - h:i A ', strtotime($announcement->created_at)) }}</h6>
                                <div class="ml-4">{{ $announcement->details }}</div>
                            </td>
                            <td>
                                <button data-toggle="modal" data-target="#announcementDetails{{ $announcement->id }}" class="btn btn-success btn-sm"><span class="fa fa-info"></span> Details</button>
                                <button data-toggle="modal" data-target="#deleteAnnouncement{{ $announcement->id }}" class="btn btn-danger btn-sm"><span class="fa fa-trash"></span> Delete</button>
                            </td>
                        </tr>

                        <div class="modal fade" aria-hidden="true" id="announcementDetails{{ $announcement->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form action="{{ route('announcements.update', $announcement->id ) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <div class="modal-header">
                                            <h5><span class="fa fa-edit"></span> Announcement Details</h5>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <label>Announcer</label>
                                                <input value="{{ $announcement->announcer }}" required type="text" class="form-control" name="announcer">
                                            </div>
                                            <div class="form-group">
                                                <label>Announcement</label>
                                                <textarea rows="10" required class="form-control" name="details">{{ $announcement->details }}</textarea>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button data-dismiss="modal" class="btn btn-secondary btn-sm"><span class="fa fa-remove"></span> Cancel</button>
                                            <button type="submit" class="btn btn-success btn-sm"><span class="fa fa-save"></span> Update</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" aria-hidden="true" id="deleteAnnouncement{{ $announcement->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form action="{{ route('announcements.destroy', $announcement->id ) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <div class="modal-header">
                                            <h5><span class="fa fa-trash"></span> Confirm</h5>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <h6>This can't be undone, do you want to proceed?</h6>
                                            </div>
                                            <div class="form-group">
                                                <label>Announcer</label>
                                                <input readonly value="{{ $announcement->announcer }}" required type="text" class="form-control" name="announcer">
                                            </div>
                                            <div class="form-group">
                                                <label>Announcement</label>
                                                <textarea readonly rows="5" required class="form-control" name="details">{{ $announcement->details }}</textarea>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button data-dismiss="modal" class="btn btn-secondary btn-sm"><span class="fa fa-remove"></span> Cancel</button>
                                            <button type="submit" class="btn btn-danger btn-sm"><span class="fa fa-trash"></span> Proceed</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        @endforeach
                    </tbody>
                </table>
            <?php include "addons/navigations/admin-footer.php";?>
            </div>
        </div>
        <?php include "addons/includes/master-js.php";?>  
        <script>
            toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": true,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            <?php
                if(session('toastType') == "announcement-updated"){
            ?>
                toastr.info("Announcemnet was updated.");
            <?php
                }
                if(session('toastType') == "announcement-added"){
            ?>
                toastr.info("Announcement added successfuly.");
            <?php
                }
                session()->put('toastType', '');
            ?>
        </script> 
    </body>
</html>

DIMS/resources/views/admin/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/admin-css.php";?>   
        <?php if(session('admin-theme') == 'dark'){ include "addons/includes/admin-dark-css.php"; }?>   
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/admin-navbar.php";?>
        <?php include "addons/navigations/admin-sidebar.php";?>
        <div class="display-container">
            <div class="modal-header" style="border-left: solid white 1px">
                <h6><span class='fa fa-tachometer'></span> Dashboard</h6>
                <!--<div>
                    <button class="btn btn-sm"><span class="fa fa-plus"></span> Create New Class</button>
                </div>-->
            </div>

            <div class="display">
                <div class="row" style="padding: 15px; margin: 0px;">
                    <div class="col-md-4">
                        <div>
                            <h3>{{ $o }}</h3>
                            <h5><span class='fa fa-users'></span> Officers</h5>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <h3>{{ $e }}</h3>
                            <h5><span class='fa fa-flag'></span> Events</h5>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <h3>{{ $m }}</h3>
                            <h5><span class='fa fa-check'></span> Meetings</h5>
                        </div>
                    </div>
                </div>
    
                <div class="modal-header" style="border-left: solid white 1px">
                    <h6><span class='fa fa-bell'></span> Annoucements</h6>
                </div>
                <br>
                <table class="table-hover">
                    <tbody>
                        @foreach ($announcements as $announcement)
                        <tr style="display: flex; justify-content: space-between; border-bottom: solid 1px gray;">
                            <td class="ml-3" style="width: 850px;">
                                <h6><span class="fa fa-user"></span> {{ $announcement->announcer }} : {{ date('M d, Y - h:i A ', strtotime($announcement->created_at)) }}</h6>
                                <div class="ml-4">{{ $announcement->details }}</div>
                            </td>
                            <td>
                                <button data-toggle="modal" data-target="#announcementDetails{{ $announcement->id }}" class="btn btn-success btn-sm"><span class="fa fa-info"></span> Details</button>
                            </td>
                        </tr>

                        <div class="modal fade" aria-hidden="true" id="announcementDetails{{ $announcement->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                     <div class="modal-header">
                                        <h5><span class="fa fa-bell"></span> Announcement Details</h5>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label>Announcer</label>
                                            <input readonly value="{{ $announcement->announcer }}" required type="text" class="form-control" name="announcer">
                                        </div>
                                        <div class="form-group">
                                            <label>Announcement</label>
                                            <textarea readonly rows="10" required class="form-control" name="details">{{ $announcement->details }}</textarea>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button data-dismiss="modal" class="btn btn-success btn-sm"><span class="fa fa-check"></span> OK</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </tbody>
                </table>
                <div id="sample">

                </div>
                <?php include "addons/navigations/admin-footer.php";?>
            </div>
        </div>
        <?php include "addons/includes/master-js.php";?>   
    </body>
</html>

DIMS/resources/views/admin/messages.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/admin-css.php";?>   
        <?php if(session('admin-theme') == 'dark'){ include "addons/includes/admin-dark-css.php"; }?> 
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/admin-navbar.php";?>
        <?php include "addons/navigations/admin-sidebar.php";?>
        <div class="display-container">
            <div class="modal-header" style="border-left: solid white 1px">
                <h6><span class='fa fa-envelope'></span> Messages</h6>
                <h6><?php if($unread > 0){ if($unread != 1){ echo $unread." unread messages"; }else{ echo $unread." unread message"; }}?></h6>
            </div>
            <div class="display message-list">
                <div class="modal-body">
                    @foreach ($mails as $mail)
                        @if($mail['uid'] != session('admin-uid'))
                            <a href="{{ route('open-message.show', $mail['uid']) }}">
                                <div class="form-group">
                                    <div class="modal-header dark-theme" style="background: white; color: #383838; padding: 5px;">
                                        <div style="width: 100%;">
                                            <h6 class="m-list <?php if($mail['read'] == "unread"){ echo 'dark-unread unread';}?>"><span class="fa fa-user"></span> <b class="mr-2">{{ $mail['name'] }}:</b> {{ $mail['position'] }}</h6>
                                            <h6 class="m-list <?php if($mail['read'] == "unread"){ echo 'dark-unread unread';}?>"><span class="fa fa-envelope"></span> {{ $mail['message'] }}</h6>
                                        </div>
                                        <div>
                                            <h6 class="t-list <?php if($mail['read'] == "unread"){ echo 'dark-unread unread';}?>"><i>{{ date('M d, Y - l @ H:i', strtotime($mail['time'])) }}</i></h6>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        @endif
                    @endforeach
                </div>
                <?php include "addons/navigations/admin-footer.php";?>
            </div>
        </div>
        <?php include "addons/includes/master-js.php";?>   
    </body>
</html>

DIMS/resources/views/admin/officers.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/admin-css.php";?>  
        <?php if(session('admin-theme') == 'dark'){ include "addons/includes/admin-dark-css.php"; }?> 
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/admin-navbar.php";?>
        <?php include "addons/navigations/admin-sidebar.php";?>
        <div class="display-container">
                <div class="modal-header" style="border-left: solid white 1px">
                    <h6><span class='fa fa-group'></span> Officers</h6>
                </div>
                <br>
                <table class="table-hover">
                    <thead>
                        <tr>
                            <td>Profile</td>
                            <td>Name</td>
                            <td>Email Address</td>
                            <td>Phone Number</td>
                            <td>Position</td>
                            <td style="width: 180px">Action</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($officers as $officer)
                            <?php if($officer->position != "Administrator"){?>
                                <tr>
                                    <td class="pl-3 table-profile"><img src="../../addons/assets/root/profiles/{{ $officer->profile }}"></td>
                                    <td class="pl-3">{{ $officer->lname }}, {{ $officer->fname }} {{ $officer->mi }}.</td>
                                    <td>{{ $officer->email }}</td>
                                    <td>{{ $officer->phone }}</td>
                                    <td>{{ $officer->position }}</td>
                                    <td>
                                        <button data-toggle="modal" data-target="#viewProfile{{ $officer->id }}" class="btn btn-success btn-sm"><span class="fa fa-user"></span> Profile</button>
                                        <button data-toggle="modal" data-target="#confirmRemove{{ $officer->id }}" class="btn btn-danger btn-sm"><span class="fa fa-trash"></span> Remove</button>
                                    </td>
                                </tr>
                            <?php }?>
                            
                        <div class="modal fade" aria-hidden="true" id="confirmRemove{{ $officer->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form action="{{ route('officers.destroy', $officer->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <div class="modal-header">
                                            <h5><span class="fa fa-trash"></span> Confirm</h5>
                                        </div>
                                        <div class="modal-body">
                                            <h6>Account of the officer will also be deleted, this can't be undone. Do you want to proceed?</h6>
                                            <hr>
                                            <div class="form-group">
                                                <input value="Name: {{ $officer->lname }}, {{ $officer->fname }} {{ $officer->mi }}." type="text" class="form-control" readonly>
                                            </div>
                                            <div class="form-group">
                                                <input value="Position: {{ $officer->position }}" type="text" class="form-control" readonly>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button data-dismiss="modal" class="btn btn-secondary btn-sm ml-1"><span class="fa fa-remove"></span> Cancel</button>
                                            <button type="submit" class="btn btn-danger btn-sm ml-1"><span class="fa fa-trash"></span> Proceed</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" aria-hidden="true" id="viewProfile{{ $officer->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <form action="{{ route('officers.update', $officer->id) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <div class="modal-header">
                                            <h5><span class="fa fa-user"></span> Profile</h5>
                                        </div>
                                        <div class="modal-body">
                                            <div class="form-group">
                                                <div class="officer-profile">
                                                    <img src="../../addons/assets/root/profiles/{{ $officer->profile }}" alt="">
                                                </div>
                                                <hr class="profile-bar">
                                                    <textarea disabled class="form-control bio" rows="3">{{ $officer->bio }}</textarea>
                                                <hr class="profile-bar">
                                            </div>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-md-5">
                                                        <label>Last Name</label>
                                                        <input type="hidden" value="{{ $officer->id }}" class="form-control" name="id">
                                                        <input required type="text" value="{{ $officer->lname }}" class="form-control" name="lname">
                                                    </div>
                                                    <div class="col-md-5">
                                                        <label>First Name</label>
                                                        <input required type="text" value="{{ $officer->fname }}" class="form-control" name="fname">
                                                    </div>
                                                    <div class="col-md-2">
                                                        <label>MI</label>
                                                        <input required type="text" value="{{ $officer->mi }}" class="form-control" name="mi">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label>Email Address</label>
                                                    <input required type="email" value="{{ $officer->email }}" class="form-control" name="email">
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-5">
                                                        <label>Phone No.</label>
                                                        <input required type="number" value="{{ $officer->phone }}" class="form-control" name="phone">
                                                    </div>
                                                    <div class="col-md-7">
                                                        <label>Position</label>
                                                        <input required type="text" value="{{ $officer->position }}" class="form-control" name="position">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button data-dismiss="modal" class="btn btn-secondary btn-sm"><span class="fa fa-remove"></span> Cancel</button>
                                            <button type="submit" class="btn btn-success btn-sm"><span class="fa fa-save"></span> Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </tbody>
                </table>
            <?php include "addons/navigations/admin-footer.php";?>
        </div>
        <?php include "addons/includes/master-js.php";?>
        <script>
            toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": true,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            <?php
                if(session('toastType') == "officer-updated"){
            ?>
                toastr.info("Officer's information was updated.");
            <?php
                }
                session()->put('toastType', '');
            ?>
        </script>  
    </body>
</html>