DIMS/routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SendMessageController;

/** this is a sample line */
use App\Http\Controllers\SampleController;

use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AdminOfficersController;
use App\Http\Controllers\AdminMessageController;
use App\Http\Controllers\AdminEventsController;
use App\Http\Controllers\AdminMeetingsController;
use App\Http\Controllers\AdminAnnouncementsController;
use App\Http\Controllers\AdminSignoutController;
use App\Http\Controllers\AdminMessageSelectedController;
use App\Http\Controllers\AdminThemeController;
use App\Http\Controllers\AdminUploadFileController;

use App\Http\Controllers\OfficerDashboardController;
use App\Http\Controllers\OfficerOfficersController;
use App\Http\Controllers\OfficerMessageController;
use App\Http\Controllers\OfficerAccountController;
use App\Http\Controllers\OfficerSignoutController;
use App\Http\Controllers\OfficerThemeController;
use App\Http\Controllers\OfficerUploadProfileController;
use App\Http\Controllers\OfficerUploadFileController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::resource('/login', LoginController::class);
Route::resource('/register', RegisterController::class);

Route::resource('admin/dashboard', AdminDashboardController::class);
Route::resource('admin/officers', AdminOfficersController::class);
Route::resource('admin/messages', AdminMessageController::class);
Route::resource('admin/events', AdminEventsController::class);
Route::resource('admin/meetings', AdminMeetingsController::class);
Route::resource('admin/announcements', AdminAnnouncementsController::class);
Route::resource('admin/signout', AdminSignoutController::class);
Route::resource('admin/theme', AdminThemeController::class);
Route::resource('admin/open-message', AdminMessageController::class);
Route::resource('admin/message-selected', AdminMessageSelectedController::class);
Route::resource('admin/send-message', SendMessageController::class);
Route::resource('admin/upload-file', AdminUploadFileController::class);

Route::resource('officer/user-dashboard', OfficerDashboardController::class);
Route::resource('officer/user-officers', OfficerOfficersController::class);
Route::resource('officer/user-message', OfficerMessageController::class);
Route::resource('officer/user-account', OfficerAccountController::class);
Route::resource('officer/user-signout', OfficerSignoutController::class);
Route::resource('officer/send-message', SendMessageController::class);
Route::resource('officer/user-theme', OfficerThemeController::class);
Route::resource('officer/user-profile', OfficerUploadProfileController::class);
Route::resource('officer/upload-file', OfficerUploadFileController::class);

/** this is a sample line */
Route::resource('sample', SampleController::class);

Route::get('/game', function() {
    return view('game');
});

Route::get('/about', function () {
    return view('about');
});

DIMS/app/Models/Officers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Officers extends Model
{
    use HasFactory;
    protected $table = 'officers';
    protected $fillable = ['lname', 'fname', 'mi', 'email', 'phone', 'position', 'bio', 'profile'];
}

DIMS/resources/views/officer/account.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/officer-css.php";?> 
        <?php if(session('user-theme') == 'dark'){ include "addons/includes/user-dark-css.php"; }?>  
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/officer-navbar.php";?>
        <div class="display-container">
            <form action="{{ route('user-account.update', $officer->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="modal-header" style="border-left: solid white 1px">
                    <h6><span class='fa fa-user'></span> Account Management</h6>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-2" style="height: 200px; text-align: center; padding: 20px;" class="profile-container">
                            <img src="../../addons/assets/root/profiles/{{ $officer->profile }}" class="profile">
                            <a style="margin-top: 20px;" class="btn btn-primary" data-toggle="modal" data-target="#browseProfile" href="#"><span class="fa fa-edit"></span> Change Profile</a>
                        </div>
                        <div class="col-md-10">
                            <label>Bio</label>
                            <br>
                            <textarea style="padding: 10px;" name="bio" cols="130" rows="9"><?php echo $officer->bio;?></textarea>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="hidden" value="{{ $officer->id }}" class="form-control" name="id">
                                <input required value="{{ $officer->lname }}" type="text" class="form-control" name="lname">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>First Name</label>
                                <input required value="{{ $officer->fname }}" type="text" class="form-control" name="fname">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Middle Innitial</label>
                                <input required value="{{ $officer->mi }}" type="text" class="form-control" name="mi">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Email Address</label>
                                <input required value="{{ $officer->email }}" type="email" class="form-control" placeholder="***@gmail.com" name='email'>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Phone Number</label>
                                <input required value="{{ $officer->phone }}" type="number" class="form-control" placeholder="+63 *** *** ****" name="phone">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Officer Position</label>
                                <input required value="{{ $officer->position }}" type="text" class="form-control" name="position">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success btn-sm"><span class="fa fa-save"></span> Save Changes</button>
                    </div>
                </div>
                <?php include "addons/navigations/officer-footer.php";?>
            </form>
        </div>
        <div class="modal fade" id="browseProfile" area-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    </div>
                    <form action="../addons/file_upload_support/uploadProfile.php?id={{ $officer->id }}&currentProfile={{ $officer->profile }}" method="POST" enctype="multipart/form-data">
                        <div class="modal-body" style="padding: 10px;">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="new_profile" id="upload" onchange="displayname(this,$(this))">
                                        <label class="custom-file-label" for="upload">Choose file</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary btn-sm"><span class="fa fa-save"></span> Save</button>
                            <button data-dismiss="modal" class="btn btn-dark btn-sm"><span class="fa fa-times"></span> Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php";?>   
        <script>
            toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-bottom-right",
                    "preventDuplicates": true,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
            <?php
                if(session('toastType') == "account-updated"){
            ?>
                toastr.info("Changes has been saved.");
            <?php
                }
                if(session('toastType') == "profile-updated"){
            ?>
                toastr.info("Your profile has been updated.");
            <?php
                }
                if(session('toastType') == "profile-invalid"){
            ?>
                toastr.warning("You uploaded an invalid file.");
            <?php
                }
                session()->put('toastType', '');
            ?>
        </script>  
    </body>
</html>

DIMS/resources/views/officer/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/officer-css.php";?>   
        <?php if(session('user-theme') == 'dark'){ include "addons/includes/user-dark-css.php"; }?>
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/officer-navbar.php";?>
        <div class="display-container">
            <div class="modal-header" style="border-left: solid white 1px">
                <h6><span class='fa fa-tachometer'></span> Dashboard</h6>
                <!--<div>
                    <button class="btn btn-sm"><span class="fa fa-plus"></span> Create New Class</button>
                </div>-->
            </div>

            <div class="display">
                <div class="row" style="padding: 15px; margin: 0px;">
                    <div class="col-md-4">
                        <div>
                            <h3>{{ $o }}</h3>
                            <h5><span class='fa fa-users'></span> Officers</h5>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <h3>{{ $e }}</h3>
                            <h5><span class='fa fa-flag'></span> Events</h5>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <h3>{{ $m }}</h3>
                            <h5><span class='fa fa-check'></span> Meetings</h5>
                        </div>
                    </div>
                </div>
    
                <div class="modal-header" style="border-left: solid white 1px">
                    <h6><span class='fa fa-bell'></span> Annoucements</h6>
                </div>
                <br>
                <table class="table-hover">
                    <tbody>
                        @foreach ($announcements as $announcement)
                        <tr style="display: flex; justify-content: space-between; border-bottom: solid 1px gray;">
                            <td class="ml-3" style="width: 850px;">
                                <h6><span class="fa fa-user"></span> {{ $announcement->announcer }} : {{ date('M d, Y - h:i A ', strtotime($announcement->created_at)) }}</h6>
                                <div class="ml-4">{{ $announcement->details }}</div>
                            </td>
                            <td>
                                <button data-toggle="modal" data-target="#announcementDetails{{ $announcement->id }}" class="btn btn-success btn-sm"><span class="fa fa-info"></span> Details</button>
                            </td>
                        </tr>

                        <div class="modal fade" aria-hidden="true" id="announcementDetails{{ $announcement->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                     <div class="modal-header">
                                        <h5><span class="fa fa-bell"></span> Announcement Details</h5>
                                    </div>
                                    <div class="modal-body" style="padding: 20px;">
                                        <div class="form-group">
                                            <label>Announcer</label>
                                            <input readonly value="{{ $announcement->announcer }}" required type="text" class="form-control" name="announcer">
                                        </div>
                                        <div class="form-group">
                                            <label>Announcement</label>
                                            <textarea readonly rows="10" required class="form-control" name="details">{{ $announcement->details }}</textarea>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button data-dismiss="modal" class="btn btn-success btn-sm"><span class="fa fa-check"></span> OK</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </tbody>
                </table>
                <?php include "addons/navigations/officer-footer.php";?>
            </div>
        </div>
        <?php include "addons/includes/master-js.php";?>
    </body>
</html>

DIMS/resources/views/officer/message.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php include "addons/includes/master-css.php";?>   
        <?php include "addons/includes/master-js.php";?>   
        <?php include "addons/includes/officer-css.php";?>
        <?php if(session('user-theme') == 'dark'){ include "addons/includes/user-dark-css.php"; }?>   
        <title>DIGITS Information Management System</title>
    </head>
    <body>
        <?php include "addons/navigations/officer-navbar.php";?>
        <div class="display-container">
            <div class="modal-header" style="border-left: solid white 1px">
                <h6><span class='fa fa-envelope'></span> Messages</h6>
            </div>
            <div class="display">
                <div class="modal-body">
                    <h6><span class='fa fa-user'></span> You are currently logged in as <b>{{ $user->fname }} {{ $user->mi }}. {{ $user->lname }}</b></h6>
                    <div class="message-board" id="scrolling_to_bottom">
                        @foreach($messages as $message)
                            <?php 
                                if($message->senderid == "admin-607add0a06445"){
                                    if($message->type != "message"){
                                        if($message->type == "fa fa-file-photo-o"){
                                            echo '
                                                <div class="l-con">
                                                    <label><span class="fa fa-user"></span> <b>Administrator:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                    <div class="form-group">
                                                        <a href="../../addons/assets/root/mfiles/'.$message->file.'"><img class="message-img" src="../../addons/assets/root/mfiles/'.$message->file.'" alt=""></a>
                                                    </div>
                                                </div>
                                            ';
                                        }else if($message->type == "fa fa-file-video-o"){
                                            echo '
                                                <div class="l-con">
                                                    <label><span class="fa fa-user"></span> <b>Administrator:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                    <div class="form-group">
                                                        <video class="message-img" controls="" name="media"><source src="../../addons/assets/root/mfiles/'.$message->file.'" type="audio/mpeg"></video>
                                                    </div>
                                                </div>
                                            ';
                                        }else{
                                            echo '
                                                <div class="l-con">
                                                    <label><span class="fa fa-user"></span> <b>Administrator:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                    <div class="form-group">
                                                        <a class="download-link" href="../../addons/file_download_support/downloadFile.php?file='.$message->file.'&name='.$message->message.'">
                                                            <div class="btn-group col-md-7">
                                                                <input disabled value="'.$message->message.'" class="form-control">
                                                                <button class="btn btn-dark '.$message->type.'" ></button>
                                                            </div>
                                                        </a>
                                                    </div>
                                                </div>
                                            ';
                                        }
                                    }
                                    else{
                                        echo '
                                            <div class="l-con">
                                                <label><span class="fa fa-user"></span> <b>Administrator:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                <div class="form-group">
                                                    <button class="btn btn-dark">'.$message->message.'</button>
                                                </div>
                                            </div>
                                        ';
                                    }
                                }
                                elseif($message->senderid == session('user-uid')){
                                    if($message->type != "message"){
                                        if($message->type == "fa fa-file-photo-o"){
                                            echo '
                                                <div class="r-con">
                                                    <label><span class="fa fa-user"></span> <b>You:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                    <div class="form-group">
                                                        <a href="../../addons/assets/root/mfiles/'.$message->file.'"><img class="message-img" src="../../addons/assets/root/mfiles/'.$message->file.'" alt=""></a>
                                                    </div>
                                                </div>
                                            ';
                                        }else if($message->type == "fa fa-file-video-o"){
                                            echo '
                                                <div class="r-con">
                                                    <label><span class="fa fa-user"></span> <b>You:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                    <div class="form-group">
                                                        <video class="message-img" controls="" name="media"><source src="../../addons/assets/root/mfiles/'.$message->file.'" type="audio/mpeg"></video>
                                                    </div>
                                                </div>
                                            ';
                                        }else{
                                            echo '
                                                <div class="r-con">
                                                    <label><span class="fa fa-user"></span> <b>You:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                    <div class="form-group">
                                                        <a class="download-link" href="../../addons/file_download_support/downloadFile.php?file='.$message->file.'&name='.$message->message.'">
                                                            <div class="btn-group col-md-7">
                                                                <button class="btn btn-success '.$message->type.'" ></button>
                                                                <input disabled value="'.$message->message.'" class="form-control">
                                                            </div>
                                                        </a>
                                                    </div>
                                                </div>
                                            ';
                                        }
                                    }
                                    else{
                                        echo '
                                            <div class="r-con">
                                                <label><span class="fa fa-user"></span> <b>You:</b> <i>'.date('M d, Y - l @ H:i', strtotime($message->created_at)).'</i></label>
                                                <div class="form-group">
                                                    <button class="btn btn-success">'.$message->message.'</button>
                                                </div>
                                            </div>
                                        ';
                                    }
                                }
                            ?>
                        @endforeach
                    </div>
                    <form action="{{ route('send-message.store') }}" method="POST">               
                        @csrf
                        @method('POST')
                        <div class="send-board">
                            <button data-toggle="modal" data-target="#browseFile" type="button" class="btn btn-success"><span class="fa fa-plus"></span></button>
                            <input autofocus="true" placeholder="Aa" required name="message" type="text" class="form-control">
                            <button type="submit" class="btn btn-success"><span class="fa fa-send"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <h6>Note: Only the administrator of the system can recieve and view your message.</h6>
            </div>
            <?php include "addons/navigations/officer-footer.php";?>
            <div class="modal fade" id="browseFile" area-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    </div>
                    <form action="../addons/file_upload_support/uploadfile.php?sen={{ session('user-uid') }}&rec={{ session('user-uid') }}&command=user" method="POST" enctype="multipart/form-data">
                        <div class="modal-body" style="padding: 10px;">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" name="new_file" id="upload" onchange="displayname(this,$(this))">
                                        <label class="custom-file-label" for="upload">Choose file</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success btn-sm"><span class="fa fa-save"></span> Save</button>
                            <button data-dismiss="modal" class="btn btn-dark btn-sm"><span class="fa fa-times"></span> Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php include "addons/includes/master-js.php";?>   
        <script>
            $('#scrolling_to_bottom').animate({
                scrollTop: $('#scrolling_to_bottom').get(0).scrollHeight}, 0);
        </script>
    </body>
</html>